travis:
  secure:
    BINSTAR_TOKEN: rdbmuJalmj/8rLHgd1YbdmTGf8KkHcU/K/4SxAd+Ry7xmfsOkzbOSyerruAwh4Vd0sGxr2FOaFqV2V99ormYPpAwbszuNFPe2iXxR1JuHiOSLJxUOsd3RKnznvhYJMBTiQV7p6t1munOaVQGI5ulVQ9eoINsZ0KUrTfMjn8d0lbD7vrO0omaIRqANcr0gKi2cGqhCTjwKsPhTbREKvIc+StBTgP7BxQdYhfKu+EWrrVxDA8KNvlUTf9GTeUgcLjcKifitiuKLBBr6AhTMe3ekZ02RDy8bGxhw/hbpnavilGvppmI2bZKUKj2W3yssT74AkJushEPhsZfz9wElROJqeT8GAAImdLNS4clrLQcJDGceh7GTZ1BB2Ec/8L2KcnzZPYP8O1Ub2OlTdh6rgmSlrPTseFhvO713vVB+SvtvfcdIx2OYpFppc2dUoiEsjQTft6LopmxZwLHSCvRsBL7gegoafh4wNwIwfomPAMRgf/SxzuHChII99TzWJKA2e9tRe7NvZfIT4KT7JfkNhdt4jK/BACZWxP0OyCyQgl9ZR6jOjDYItHiaCoOWEhSAMA3eTG5x+VIZ8wQqDAb8E6oSYmIPSbu64OQNeqIRpgIvxZK655+ArCrGxb60zp2t4GIqobDJJktNBdzIKxw5VxjIkFrNlfYhkiV27vdgO1y03g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
