travis:
  secure:
    BINSTAR_TOKEN: PHlezZXwYAq0Lk7BUbjUEoVYqVksdjcuB+I+MY4/s4lMo86R7qFRnBR/vFCfaysM+3Sotv9azWijVKQkbuIm/I23D776ppl8TIpJiNvSg3cayNlHA1RFG6Thl96Kg/Yj4XdJXYnl8UNxsKPsFWwERHB/83WC+s3MZyCea3HMRB/IKMsioL1bdLCdHKc1yK5GYU5AN3UYgCWre0A2ihu6mKXlO0SY10GibHbFc1M6+VKeN9Z0QoC07nC2hBNYY2m0WhNTu9/7uCX+2+lP68AStppSpZ07vgXJfrhX+OTXKkJ24xmidXO8caWHKRwZRkloW8+IylF5QvXlD1FlkFPjf9EINUDYT/ypLiXFLn5/WqXmnVFdtFLD49PgA4ze/1S/4jrDHpNOF7/jVZUcv8HuHRJghux385vzi+nGLc5NTGtSSOUaYaIGWvEm0RRpEsK2eSJGvy3hE4tgTs5TUcFMV83OBXsZHgxvjaQvSBYn4qwPD7G2+kRUT9UYytqzmLTeIztltRqlAKqNPYI6hpelgWepGQ0dD4pdWsrRJTXg2xwcIM4TajlTJVQ9oy64mNjqxBwK30tklXll7OJy2u4T0LvoKYaa04D9f+Ii1Hw7HpCv7JeSoOkoVmJbQ1wveeiFacXEXPRzPVEdy71E6ELWjLQ5cu91kn3Uc2mgdub96rg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
