travis:
  secure:
    BINSTAR_TOKEN: gxC+mautpjJGYEl1SzTm3RnQydofQK3FpnNgQ/LvXMmnYJj1xUa1RCdaZBHcmbYPuXDxF/gkdp5BUuidRkme7ifmgTs3LO3p3h9O6iHgBQy0VKJE0jMNqFfoJnTGYZoQt4z3MbPJ3k2epn1a2mh5piIaUBMhU4ik++VuBHoqFCkxTjm8Bb4Oaw1lpHT1pYWGhaxAFx+TQkQP7NNJ2nGBs1FfJDY/h2wiYouz2epyghyyJDd2dIi/UrCdlJSWI0TaES5LGLqJ+zeRUAAQCX0Noa8jTxj8jxVdsgL2XfvN7BKUGY/F73iFCh5TZQCoQukauOb3i4ycdSJrZWvXkNw3L98ZYCjtj3ELwSDZs0EDaUQPzzgSDRrKXDeA1fPEEyCLwqicULx0ye6i2YwKciQR31JFK68UGj534YFtNbyfkZ2SFvfitaWTzr8HNhABIZxEJerQjcQrO+RGALFGcROvTw0ho5Zac1a+ZEenxLYa03X+aRNSFHw5pQ9QTkO2/PBV+vIsiHFQ3TDP4clWBJHxLFjySsHUE3EDKTLX/t4c0cs80sJImmt9VeH+kpNTFNx1reCHR8mQDjWBFumEsJ8Lu/YKQlvlDec1OKiBdJPI0kJrAsdsveyvIREzcnoqhIOqApCn7iNiIsCKK9MNX9EoSjtZERfbTmlf+xLrlWiEx94=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
